# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - movieapi-ml-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DA3DADDE3ED04EEA96FCF9434527AA5A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32DB54EE63954B58BCCD3298BBB71446 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5FC2A0E3E66745A4B65101C0B3F4FB27 }}

      # LANGKAH BARU: Menghentikan aplikasi untuk menghindari error 409 Conflict
      - name: Stop Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp stop --name 'movieapi-ml-service' --resource-group 'bangraply-azure-development'
            
      # LANGKAH DIMODIFIKASI: Deploy menggunakan file zip secara langsung
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'movieapi-ml-service'
          slot-name: 'Production'
          package: 'release.zip'

      # LANGKAH BARU: Memulai kembali aplikasi setelah deployment selesai
      # 'if: always()' memastikan langkah ini selalu berjalan, bahkan jika deployment gagal
      - name: Start Azure Web App
        if: always()
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp start --name 'movieapi-ml-service' --resource-group 'bangraply-azure-development'